USE fp2_23b;

CREATE TABLE Players (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  salt VARCHAR(255) NOT NULL,
  victories INT DEFAULT 0,
  defeats INT DEFAULT 0
);

CREATE TABLE Games (
  id INT AUTO_INCREMENT PRIMARY KEY,
  winnerId INT,
  loserId INT,
  game_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (winnerId) REFERENCES Players(id),
  FOREIGN KEY (loserId) REFERENCES Players(id)
);

CREATE INDEX idx_name ON Players (name);
